server:
  port: 2001

eureka:
  instance:
#    metadata-map:
#      management.context-path: ${management.context-path}
    statusPageUrlPath: ${management.contextPath}/info
    healthCheckUrlPath: ${management.contextPath}/health
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
