server:
  port: 2002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


#routes' path and serviceid must set up together

zuul:
#  prefix: /api
  strip-prefix: true
#  ignoredServices: '*'
#  routes:
#    compute-service:
#      serviceId: compute-service
#      url: http://localhost:2001
#      path: /compute-service/**
#    static:
#      path: /static/*


hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 6000